<?php
// $Id: imagecache_dropshadow.module, v 0.1, 2009/04/01 20:30:37, skilip Exp $;

/**
 * @file
 * 
 * Imagecache Dropshadow.
 */


/**
* Implementation of hook_imagecache_actions.
*
* @return array
*   An array of information on the actions implemented by a module. The array contains a 
*   sub-array for each action node type, with the machine-readable action name as the key. 
*   Each sub-array has up to 3 attributes. Possible attributes:
* 
*     "name": the human-readable name of the action. Required.
*     "description": a brief description of the action. Required.
*     "file": the name of the include file the action can be found 
*             in relative to the implementing module's path.
*/
function imagecache_dropshadow_imagecache_actions() {
  $actions = array(
    'dropshadow' => array(
      'name' => t('Drop shadow'),
      'description' => t('Define the size of the working canvas and background color, this controls the dimensions of the output image..'),
      'file' => 'dropshadow.inc',
    ),
  );

  return $actions;
}

/**
 * Need to register the theme functions we expect to use
 */
function imagecache_dropshadow_theme() {
  return array(
    'dropshadow' => array(
      'file'      => 'dropshadow.inc',
      'arguments' => array('element' => NULL),
    ),
  );
}